services:
  travelplanningservice:
    container_name: travelplanningservice
    build: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/traveling"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"

  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: traveling
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9001:80
    depends_on:
      budgetplanning-db:
        condition: service_healthy
    environment:
      PMA_HOST : db
